### ISSUE TITLE
[功能需求]bossbar-倒计时比赛结束

### ISSUE THREAD

**Issue by YuanYuanOwO** [carm-outsource/FishContest#1]
**功能简述**

在比赛开始时，跟随着左下角的提示出现，建议添加一个BossBar比赛时长倒计时
例如 `本次钓鱼大赛还有 X分X秒 结束`

**需求来源**

中途进来的玩家有可能不知道该子服/服务器正在进行钓鱼大赛

**功能参考**(可选)

![djs](https://user-images.githubusercontent.com/81153017/222942369-4d6dab35-8c16-4b99-b2e3-cc4df989d7aa.png)
10分钟之后是9分59秒，以此类推

**附加内容**

**Comment by CarmJos** [comment]
在后续版本中，将提供单独的 PlaceholderAPI 变量，以支持查询当前比赛的剩余时间。

稍后，您可以搭配现有的Bossbar插件实现倒计时效果。

**Comment by CarmJos** [comment]
您好，该功能将在 1.0.0 发版时支持。
